// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZe8ms0NN4mzz7jhl1WmCgMroE7ARhkws',
    appId: '1:26434861411:web:18978df04c96acc7b23b56',
    messagingSenderId: '26434861411',
    projectId: 'practicaflutter2',
    authDomain: 'practicaflutter2.firebaseapp.com',
    storageBucket: 'practicaflutter2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMfpc5tQQwTT0wyqlAX1mWaC8ieCH8-cc',
    appId: '1:26434861411:android:59e54eebbaaf73c5b23b56',
    messagingSenderId: '26434861411',
    projectId: 'practicaflutter2',
    storageBucket: 'practicaflutter2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPJQyATRHEYfQFo5Bd_NaFCs1FnroURrg',
    appId: '1:26434861411:ios:ff3ae6c3811682abb23b56',
    messagingSenderId: '26434861411',
    projectId: 'practicaflutter2',
    storageBucket: 'practicaflutter2.appspot.com',
    iosBundleId: 'com.example.practica1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPJQyATRHEYfQFo5Bd_NaFCs1FnroURrg',
    appId: '1:26434861411:ios:ff3ae6c3811682abb23b56',
    messagingSenderId: '26434861411',
    projectId: 'practicaflutter2',
    storageBucket: 'practicaflutter2.appspot.com',
    iosBundleId: 'com.example.practica1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZe8ms0NN4mzz7jhl1WmCgMroE7ARhkws',
    appId: '1:26434861411:web:30d4317a53953cbcb23b56',
    messagingSenderId: '26434861411',
    projectId: 'practicaflutter2',
    authDomain: 'practicaflutter2.firebaseapp.com',
    storageBucket: 'practicaflutter2.appspot.com',
  );
}
